### ISSUE TITLE
Need a small improvement to the flatten name matching

### ISSUE THREAD

**Issue by RudeySH** [expressmapper/ExpressMapper#147]
I just started using ExpressMapper and I'm already heavily relying on the flatten functionality. I like how it maps `src.Inner.SomeProperty` to `dest.InnerSomeProperty`. However, I am wondering, why can't it map `src.Inner.SomeProperty` to just `dest.SomeProperty` in cases where the outer class does not have a `SomeProperty` himself?

**Comment by RudeySH** [comment]
@JonPSmith Any thoughts on this? I noticed you were the one who implemented Flatten, you might have an answer for me :)

**Comment by JonPSmith** [comment]
Hi @RudeySH,

The flattening I added is fairly basic, but I have written a [long article that explains how it works](http://www.thereformedprogrammer.net/flattening-entity-framework-relationships-with-expressmapper/). 

I was planning to change from [AutoMapper](https://github.com/AutoMapper/AutoMapper) to  ExpressMapper, but two things have stopped me from doing that:
- ExpressMapper isn't updated very often. Specifically it isn't currently usable with .NET Core (see issue #143 and #135). AutoMapper is very well supported.
- AutoMapper has significantly improved its initial set up performance, which was the problem that made me look at ExpressMapper.

**Comment by RudeySH** [comment]
Thanks @JonPSmith . In the meanwhile I have done some experimenting with ExpressMapper and I already feel like I should switch to AutoMapper because of all the issues I'm running in to.

Slightly off topic, but are the performance tests between ExpressMapper and other mappers purely focussed on the initial set up performance? I will maily be using mapping for EF queries and I am worried that AutoMapper will slow my queries down.

**Comment by JonPSmith** [comment]
Hi @RudeySH,

It was a while ago but ExpressMapper and AutoMapper LINQ->EF were the same. They should produce similar LINQ and its then up to EF to convert it.

**Comment by RudeySH** [comment]
It turns out this is pretty easily done in AutoMapper. https://github.com/AutoMapper/AutoMapper/issues/2489

**Comment by JonPSmith** [comment]
Good to know. Thanks.
