### ISSUE TITLE
Add ServiceStack to Benchmarks

### ISSUE THREAD

**Issue by tig2810** [expressmapper/ExpressMapper#23]
Hello,

It would be great to add ServiceStack's auto-mapping to the benchmarks. 

thank you

**Comment by bogatykh** [comment]
We have reviewed your idea and decided not to implement this comparison. ServiceStack is a web service library, not a mapping framework and has very limited mapping functionality. Actually, there is no even mapping registration, only dynamic auto map.

That is why it will be implemented only in a few tests maybe one test which doesn't make sense.
But still if you have any other concerns please let us know - we'd gladly consider any improvement.
