### ISSUE TITLE
Unit Testing and Type Registration Error

### ISSUE THREAD

**Issue by mantzas** [expressmapper/ExpressMapper#27]
Hi,

i am using xUnit2.
In my constructor i do my registrations (test setup) and Mapper.Complile() and my tests throw exceptions like the following:

Result StackTrace:	
at ExpressMapper.MappingService.Register[T,TN]() in c:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingService.cs:line 34
   at ExpressMapper.Mapper.Register[T,TN]() in c:\SourceCode\ExpressMapper\ExpressMapper NET40\Mapper.cs:line 49
   at Bitusion.Overlook.Repository.RepositoryMapperConfig.Configure() in D:\dev\projects\Overlook\src\overlook\Bitusion.Overlook.Repository\RepositoryMapperConfig.cs:line 12
   at Bitusion.Overlook.Web.ModelMappingConfig.Configure() in D:\dev\projects\Overlook\src\overlook\Bitusion.Overlook.Web\App_Start\ModelMappingConfig.cs:line 12
   at Bitusion.Overlook.Web.Tests.Unit.Controllers.ApplicationControllerTests..ctor() in D:\dev\projects\Overlook\src\overlook\Bitusion.Overlook.Web.Tests.Unit\Controllers\ApplicationControllerTests.cs:line 30
Result Message:	System.InvalidOperationException : Mapping from Bitusion.Overlook.Data.Models.ApplicationUserDbModel to Bitusion.Overlook.Business.Contracts.Models.ApplicationUserModel is already registered

Probable the way the tests run the setup is called multiple times and the lib does not allow multiple registrations of mappings. 

Maybe it should check whether the registration exists in order to avoid double registration and exception, or the new one should replace the old one. 
Maybe a UnregisterAll? Along with a Reset?

**Comment by anisimovyuriy** [comment]
Dear Mantaz,

Yes we have this check if the same mapping is registered more than one time. UnregisterAll and Reset actually are the same - is just clearing the internal cache. So here we have 2 solutions:
1) Wait for the fix replacing new one with the old one mapping's registration. - please give us sometime (1 day) to decide but I think you made a reasonable point here.
2) Fix your tests that have been called mapping's registration multiple times. - if it is not possible in your case - we'll try to fix the first point ASAP.
Please let us know if you have some additional concerns.

Thanks!

**Comment by anisimovyuriy** [comment]
Dear Mantzas,

I think it is right to throw an exception when the same mapping has been registered twice instead of using replacement of the old mapping with a new one as it could lead to more painful outcome. So I think it would be right thing to do to fix your code and use mapping registration only once. Still if you some concerns please let us know we'd be glad to concider any other suggestions.

Thanks

**Comment by mantzas** [comment]
Dear @anisimovyuriy,

it seems that the problem did not originate in my tests and not by you code.
The test runner (xunit.runner.visualstudio nuget) i used was displaying this behavior. When i tried another one all went well!.
Sorry for the troubles!
Really nice job!

Regards!

**Comment by mantzas** [comment]
i will fix the tests. thanks, nice work by the way!

**Comment by anisimovyuriy** [comment]
Thanks Mantzas!
