### ISSUE TITLE
I can't install the package in my PCL

### ISSUE THREAD

**Issue by fcogutierrez** [expressmapper/ExpressMapper#35]
Hello.

I want to install this dependency in my PCL project, but I am getting this error:

![d](https://cloud.githubusercontent.com/assets/8028313/9600722/fd0079a0-509c-11e5-9ebb-ddbf66be57a4.png)

I want to use this library in my Xamarin project, in a Portable Class Library.

Thanks.

**Comment by bogatykh** [comment]
Portable library is not yet supported. But we are planning this for future releases.

**Comment by fcogutierrez** [comment]
ok :)

Another mapper framework as temporal alternative?

I will look forward your future releases.

**Comment by anisimovyuriy** [comment]
FIXED and will be included in 1.1 release
