### ISSUE TITLE
Support for mapping ObservableCollection

### ISSUE THREAD

**Issue by anisimovyuriy** [expressmapper/ExpressMapper#39]
This is not working for me, and I have the last stable version. I am gettnig this error:

 "Expression of type 'System.Collections.Generic.List`1[WCF.WcfService.SaleLineItem]' cannot be used for assignment to type
 'System.Collections.ObjectModel.ObservableCollection`1[WCF.WcfService.SaleLineItem]'"

I only want to map this element:

    public class Sale
    {
        public IEnumerable<SaleLine> SaleLines { get; set; }
    }

To this one:

    public class SaleHeaderItem
    {
        public ObservableCollection<SaleLineItem> SaleLineList { get; set; }
    }

I am doing something like this:

            Mapper.Register<Sale, SaleHeaderItem>()
                .Member(dest => dest.SalesLineList, src => src.SaleLines);
            Mapper.Register<SaleLine, SaleLineItem>();

            Mapper.Compile();

**Comment by fcogutierrez** [comment]
When do you think you will upload a new release with this fixed?

**Comment by anisimovyuriy** [comment]
Hey fcogutierrez,
It has already been fixed! New release will be around next week.

**Comment by anisimovyuriy** [comment]
Fixed - will be included in 1.5 release

**Comment by fcogutierrez** [comment]
Thanks a lot mate!! :)
