### ISSUE TITLE
Nullable nested properties throws NullReferenceException

### ISSUE THREAD

**Issue by anisimovyuriy** [expressmapper/ExpressMapper#4]
Mapper.Register<ObjectItem, ObjectItemDetailsViewModel>()
                .Member(dest => dest.AddressName, src => src.Address.Name)
                .Member(dest => dest.SellerFirstName, src => src.Seller.FirstName)

If src.Address equals is null or src.Seller is null - throws NullReferenceException...

**Comment by bogatykh** [comment]
Unit test added. Issue tested.
