### ISSUE TITLE
Error when viewmodel extends model

### ISSUE THREAD

**Issue by CheloXL** [expressmapper/ExpressMapper#43]
Hi, 
I just stumbled upon the following issue: I have an object A, with some properties. One of the properties is an IEnumerable&lt;C&gt;. For my viewmodel, I have object B extends A.

When I register my mapping .Register&lt;A, B&gt;() and then run a .Compile(), EM throws the following exception: **There is no mapping has bee found. Source Type: C, Destination Type: C.**

I don't think I have to register a mapping from C to C...

PD: Nitpick text correction. The text should read "No mapping has been found between Source Type: A and Destination Type: B".

**Comment by CheloXL** [comment]
I just updated the comment... Git doesn't notify you about changes in the text...

**Comment by bogatykh** [comment]
Bug in 1.1. Will be fixed in next release.

**Comment by anisimovyuriy** [comment]
Fixed! - Will be included in 1.5 release.

**Comment by CheloXL** [comment]
Do you have an ETA for 1.5?

**Comment by anisimovyuriy** [comment]
Dear CheloXL,

approx. September the 8th

Thanks

**Comment by fcogutierrez** [comment]
Hello Anisimovyuriy, are you going to upload 1.5 release? :-)

**Comment by anisimovyuriy** [comment]
Dear fcogutierrez,

My apologies I have some contingencies. Anyways I'm going to do that today.

Thanks for understanding!
