### ISSUE TITLE
Cannot resolve symbol "MapTo"

### ISSUE THREAD

**Issue by frost555** [expressmapper/ExpressMapper#44]
I can't compile the following code (c# console application with ExpressMappre 1.1.2 nuget package.
https://gist.github.com/frost555/bf17d07191816b810e04

I get the the following error: Cannot resolve symbol "MapTo"
What am i doing wrong?

**Comment by anisimovyuriy** [comment]
Please use new version Expressmapper 1.5 - there is an extension method "Map" under "Expressmapper.Extensions" namespace. Please let me know if it doesn't solve your problem.

**Comment by waynebrantley** [comment]
Additionally, all your info on home page refers to MapTo<>, but it appears to be called Map<> now?
