### ISSUE TITLE
Multiple .After handlers

### ISSUE THREAD

**Issue by tompazourek** [expressmapper/ExpressMapper#45]
I am trying to use multiple `.After` handlers and they don't seem to work correctly. Only one of the handlers gets called (not sure what decides which one).

```csharp
Mapper.Register<Foo, Bar>()
    .After((src, dest) => afterHandler1(src, dest))
    .After((src, dest) => afterHandler2(src, dest))
    .After((src, dest) => afterHandler3(src, dest));
```

When I change the code this way, it works:

```csharp
Mapper.Register<Foo, Bar>()
    .After((src, dest) =>
        {
            afterHandler1(src, dest);
            afterHandler2(src, dest);
            afterHandler3(src, dest);
        });
```

This is counter-intuitive and I think that the first sample should either work as well, or at least throw exception to avoid bugs.

**Comment by bogatykh** [comment]
We will throw an exception. Reason we can't implement multiple Before or After handlers is because we don't know in which order they should be executed.

**Comment by tompazourek** [comment]
Great! Thanks.

**Comment by bogatykh** [comment]
Implemented. Will be available in next release.

**Comment by tompazourek** [comment]
Thank you! :+1:
