### ISSUE TITLE
How to map to destination of array?

### ISSUE THREAD

**Issue by damiangreen** [expressmapper/ExpressMapper#47]
Consider this code.

    Mapper.Register<Type1ReportPermissions[], Permission[]>()
                .Member(dst => dst, src => src.GroupBy(p => p.ClientId)
                    .Select(g => new Permission
                    {
                        ClientId = g.Key,
                        RoleIds = g.Select(r => r.RoleId)
                            .ToArray()
                    }).ToArray());

On Compile, the error is thrown

    "MemberExpression should return one of the properties of destination class"

How does one go about mapping from a collection of one type to a collection of another?

**Comment by anisimovyuriy** [comment]
Dear damiangreen,

Thanks a lot for your input and my apologies for my late response!
Mapper doesn't have functionality to register collection types and there is a right logical purpose.
Expressmapper can resgister class to class mapping ```Mapper.Register<Source, Destination>``` and then you could use any collections ```Mapper.Map<List<Source>, Destination[]>``` which is quiet right. But when it comes to map collection types in a custom way there is special functionality for it:
```Mapper.RegisterCustom<Type1ReportPermissions[], Permission[]>(
src => src.GroupBy(p => p.ClientId)
                .Select(g => new Permission
                {
                    ClientId = g.Key,
                    RoleIds = g.Select(r => r.RoleId)
                        .ToArray()
                }.Map<Permission, Type1ReportPermissions>()));```
But I'd rather recommend to use: ```Mapper.RegisterCustom<Type1ReportPermissions[], Permission[], CustomTypeMapper>();``` where CustomTypeMapper it is your custom class that implements: ```ICustomTypeMapper<T, TN>``` interface to make code loosly coupled or other interface + class implementation.
Or the best case to implement you code in a different way:
In your client code you'll have the following method or just code without method:
```Type1ReportPermissions[] MapPermissions(Permission[] permissions)
{
           return permissions.GroupBy(p => p.ClientId)
                .Select(g => new Permission
                {
                    ClientId = g.Key,
                    RoleIds = g.Select(r => r.RoleId)
                        .ToArray()
                }.Map<Permission, Type1ReportPermissions>());
}
``` 
I'd rather avoid to put this kind of code inside of Mapper but rather leave it in a client code and use mapping as it is intended (see code above).

Please let me know if you have any other questions.

Thanks,
Yuriy

**Comment by damiangreen** [comment]
Many thanks @anisimovyuriy . Much appreciated
