### ISSUE TITLE
Target nested objects not getting initialized?

### ISSUE THREAD

**Issue by shay1e** [expressmapper/ExpressMapper#48]
Hi there :)

Please consider the following model:

    public class Target
    {
        public TargetNestedClass TargetNested;
    }

And mapping:

	var mapper = Mapper.Register<Source, Target>()
		.Member(p => p.TargetNested.TargetNestedInt,
			p => p.SourceNested.SourceNestedInt)

A call to `Mapper.Map(source, target);` would result in an null reference exception, since `target.TargetNested` is null when `target` is internally passed to the generated BinaryExpression. Am I missing something here? Or should the client make sure that all possible paths are initialized? I saw that the destination expression is added an initialization node (`GetDestionationVariable()`) when declaring it's mapping, but from what I understand (and experiencing) it's applied only to the root parameter. Am I wrong about that?

**Comment by anisimovyuriy** [comment]
Dear shay1e,

Thanks for your input and question!
You did amost right thing except that you try to delegate mapping of the nested class member to the root one which is not quiet right.
Consider this mapping registration:
```
var mapper = Mapper.Register<Source, Target>()
    .Member(p => p.TargetNested, p => p.SourceNested);
var mapper = Mapper.Register<SourceNestedClass, TargetNestedClass >()
    .Member(p => p. TargetNestedInt, p => p.SourceNestedInt);
```

Please let me know if it solves your problem.

Thanks,
Yuriy

**Comment by shay1e** [comment]
anisimovyuriy,

Thank you so much for the replay :)

Your comment makes a lot of sense!
I will do that today and come back.

Shay.

**Comment by shay1e** [comment]
Yes, that did it :)
