### ISSUE TITLE
Map between IEnumerable<> and ICollection<> or IList<>

### ISSUE THREAD

**Issue by maurodx** [expressmapper/ExpressMapper#54]
Trying to map between an `IEnumerable<T>` and an `ICollection<TN>` or `IList<TN>` the result is an exception because QueryableExpression in TypeMapper is null.

The problem is caused by `SourceTypeMapper` and the `Expression.Bind` that can work (also in plain c# code) if we do

`dest.ACollectionProperty= src.AIEnumerableProperty;`

we need to do

`dest.ACollectionProperty= new Collection<TN>(src.AIEnumerableProperty);`

How can this be solved?

in my domain I have collection interfaces everywhere and I have to map between EF6 and this model objects.

**Comment by anisimovyuriy** [comment]
Dear maurodx,

Thanks a lot for that marvellous input :)
Just to clarify we are talking about ```.Project``` or just standard ```Mapper.Map```.
If it is ```.Project``` - I've just fixed and today I'm gonna release new version with that hotfix.

Looking forward to hearing from you,
Yuriy

**Comment by anisimovyuriy** [comment]
Hotfix has been fixed and published in 1.6.2 for IQueryable.Project. Please let me know if it fixes your issue.

Thanks,
Yuriy

**Comment by anisimovyuriy** [comment]
Dear maurodx,

I'm closing the issue as I hope it is solved please reopen it if it is not!

Thanks,
Yuriy
