### ISSUE TITLE
Mapping engine interface

### ISSUE THREAD

**Issue by bogatykh** [expressmapper/ExpressMapper#6]
Mapper Interface is required to be used in unit tests. IMapper (or similar name) with all Mapper static class functionality. Mapper static class should stay static, but instance of IMapper Interface implementation created as a private static variable.

**Comment by anisimovyuriy** [comment]
Thanks Dmitry,

Definetely solution will be refactored as there are many points to refactor. You remark has a good point and it'll be implemented.

**Comment by bogatykh** [comment]
IMappingService interface and MappingService implementation introduced.
