### ISSUE TITLE
Collection with destination child data not mapping correctly

### ISSUE THREAD

**Issue by bogatykh** [expressmapper/ExpressMapper#60]
public class ObjectA
{
    public string Code { get; set; }
}

public class ObjectB
{
    public string Code { get; set; }

    public List<ObjectA> Childs { get; set; }
}

public class DbObjectA
{
    public string Code { get; set; }
}

public class DbObjectB
{
    public string Code { get; set; }

    public DbObjectA[] DbObjectA { get; set; }
}

static void Main(string[] args)
{
    Mapper.Register<DbObjectA, ObjectA>();
    Mapper.Register<DbObjectB, ObjectB>().
        Member(x => x.Childs, x => x.DbObjectA);
    Mapper.Compile();

    var objectB1 = new DbObjectB()
    {
        Code = "ObjectB1",
        DbObjectA = new DbObjectA[] { new DbObjectA() { Code = "ObjectA1" } }
    };

    var objectB2 = new DbObjectB()
    {
        Code = "ObjectB2",
        DbObjectA = new DbObjectA[] { new DbObjectA() { Code = "ObjectA2" } }
    };

    DbObjectB[] objectBArr = new DbObjectB[] { objectB1, objectB2 };

    List<ObjectB> result = new List<ObjectB>();

    Mapper.Map<DbObjectB[], List<ObjectB>>(objectBArr, result);
}

both result[0].Code and result[1].Code will contain "ObjectB2" - bug.
also, result[0].Childs will contain the same data as from result[1].Childs.

**Comment by bogatykh** [comment]
Bug is not reproducible in version 1.0.3

**Comment by anisimovyuriy** [comment]
#56, #58

**Comment by anisimovyuriy** [comment]
Fixed and will be included in 1.7 release
