### ISSUE TITLE
Code formatting standards?

### ISSUE THREAD

**Issue by petertiedemann** [expressmapper/ExpressMapper#66]
In trying to contribute to this project i hit a small annoyance with code formatting as the code standards are drastically different from my normal settings. Does anyone have a settings file for visual studio that can be used (and perhaps even for resharper?).

**Comment by anisimovyuriy** [comment]
Hey petertiedemann,

I'm just using standard resharper settings that's it.

Br,
Yuriy

**Comment by petertiedemann** [comment]
Didn´t realize that the standard microsoft settings had so much indentation and placed the { on a newline :(

Still, it might be an idea to commit a solution specific resharper settings file to the repository as described here:

https://www.jetbrains.com/resharper/help/Sharing_Configuration_Options.html#d261617e130

In that way, everybody using resharper should get the same settings.

Unfortunately i don´t think the indentation level is handled by Resharper, but luckily there seems to be a plugin for VS that can do it (using a committed settings file) calle EditorConfig:

https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328

and there is also rebracer (in case people don´t have resharper):

https://visualstudiogallery.msdn.microsoft.com/410e9b9f-65f3-4495-b68e-15567e543c58

Can i convince you to commit the resharper settings, then i will try to generate an EditorConfig file.

**Comment by petertiedemann** [comment]
Btw, what version of the VS build tools should be supported? I am using VS2015 and the included C# compiler supports a lot of syntactic sugar that is nice to use, but i am careful in applying such changes in case this projects need to be able to compile with earlier versions?

**Comment by anisimovyuriy** [comment]
Hey Peter,

Thanks a lot for improvements I'm all up for that - just let me check and I'll merge your pull request.

Regarding VS 2015 - I'm using it as well the thing is that some things are not compatible with .Net40 as an example please take a look: http://stackoverflow.com/questions/28921701/does-c-sharp-6-0-work-for-net-4-0

Actually I was going to upgarde to new compile features that have support for .Net - so if you want to do it go for it - I'd really appreciate but please make sure that they are supported!

**Comment by petertiedemann** [comment]
There are several source-code only features that does not affect which runtimes are supported, like getter only auto-properties and "using static". Its just that resharper keeps suggesting clean-ups based on C# 6.0, and before i started applying them in code i touch, i wanted to ensure that it was okay that it requires VS2015 build tools. But seeing as VS2015 is free for open source projects, i don´t see why anyone would complain.

**Comment by anisimovyuriy** [comment]
Hey Peter,

Well it affects only people that are contributing to the source code though not who uses the library itself as a reference and it is compiled to the same MSIL code... So I think we are ok with that we have a requirement for contributors using VS2015 or use previous version with Roslyn.

So go fo it man :)

Thanks,
Yuriy
