### ISSUE TITLE
Nullable to NonNullable mappings and vice versa - throws exception

### ISSUE THREAD

**Issue by anisimovyuriy** [expressmapper/ExpressMapper#8]
Nullable to NonNullable mappings and vice versa - throws exception
e.g. - product.weight - decimal? and productViewModel.weight - decimal

Register<Product, ProductViewModel>()
           .Member(dest => dest.Weight, src => src.Weight);

Member specification just for illustration purposes.

**Comment by bogatykh** [comment]
Unit test added. Issue tested.
