### ISSUE TITLE
Lists are copying by reference instead of duplicating

### ISSUE THREAD

**Issue by bzuillsmith** [expressmapper/ExpressMapper#83]
Maybe I'm missing something obvious or mistaken about how this should code function. The code below shows a test of the ```.Map(src, dest)``` functionality. The Assert fails. Why?

```
// NUnit Test
[Test]
public void ShouldNotBeTheSame()
{
    var mapper = new MappingServiceProvider();

    mapper.Register<AClass, AClass>();
    mapper.Register<BClass, BClass>();

    var a = new AClass()
    {
        AProperty = "test",
        InnerObjects = new List<BClass>() { new BClass { BProperty = "test2!" } }
    };

    var a2 = new AClass();
    mapper.Map(a, a2);
    // Should be different instances with the same data
    Assert.AreNotSame(a.InnerObjects, a2.InnerObjects); //Fails here, but why?
}

public class AClass
{
    public string AProperty { get; set; }
    public List<BClass> InnerObjects { get; set; }
}

public class BClass
{
    public string BProperty { get; set; }
}
```

**Comment by bzuillsmith** [comment]
Seems to be specific to that signature of ```.Map``` because ```var a3 = mapper.Map<AClass, AClass>(a);``` works properly.

**Comment by anisimovyuriy** [comment]
Dear @bzuillsmith,
Thanks for your input!
Mapping with destination and without destination is different compiled code. Mapping without destination less heavy, mapping with destination - tries to reuse existing object on destination side. But in case you map with destination the same type - it should work like a deep copy. Let me check and I'll get back to you ASAP.

Thanks.

**Comment by anisimovyuriy** [comment]
Dear @bzuillsmith,

Actually the should be the same as you are using mapping with destination: ```mapper.Map(a, a2);```.
If you want deep copy then use ```var a2 = mapper.Map(a);```

Let me know if you have any concerns.

Thanks,
Yuriy

**Comment by bzuillsmith** [comment]
Ah, I see. I wanted to do a deep copy using ```mapper.Map(a, this)``` but perhaps I can do it in two steps: ```mapper.Map(mapper.Map(a), this)```? I'll give it a try. Thanks

**Comment by anisimovyuriy** [comment]
Yeah I think you are on a right way.

**Comment by shay1e** [comment]
It'd be interesting to compare that deep cloning method to other high performance libraries.

**Comment by anisimovyuriy** [comment]
Sure @shay1e  - after all p1 - I'll do it :)

Thanks!

**Comment by sgf** [comment]
@anisimovyuriy
Hi,was ExpressMapper support Deep Copy now?
i seen a project can do it.
https://github.com/ReubenBond/DeepCopy
