### ISSUE TITLE
I'm thinking of building a 'flattening' extension to ExpressMapper

### ISSUE THREAD

**Issue by JonPSmith** [expressmapper/ExpressMapper#85]
Hi,
I have an open-source project called [GenericServices](https://github.com/JonPSmith/GenericServices) which uses [AutoMapper](https://github.com/AutoMapper/AutoMapper) to project Entity Framework LINQ commands. 

I have been following your work and am considering converting to ExpressMapper mainly for its speed. However ExpressMapper doesn't support [flattening](https://github.com/AutoMapper/AutoMapper/wiki/Flattening) at the moment. I have build a [simple flattener](https://github.com/JonPSmith/TryMappers/blob/master/TryMappers/Flatteners/FlattenMapper.cs) which looks hopeful - see [this test](https://github.com/JonPSmith/TryMappers/blob/master/TryMappers/UnitTests/Test20FlattenMapper.cs) for what it does. However I don't think I can do it from the outside of your project as some of the things I need aren't public.

I still need to check your LINQ implementation but before I put any more time in this I would really like your advice. My questions are:

1. Does flattening sound like a useful feature to add to ExpressMapper?
2. What do you think is the best way to call it up? I'm thinking of something like your `.CaseSensitive(true)` extension on `Mapper.Register`, e.g. `.Flatten()`.
3. It is important that users can override the flatten with further `.Member` or `.Ignore` extensions. Not too sure how to do that, as some of the parts are internal.

I'm happy to do some work on the project (work permitting), or just fork and have my own version (but not that nice as it is likely to fall behind). Let me know what you think.

PS. My very limited tests show that your LINQ projection is about the same speed as AutoMapper LINQ projection, but your setup is about eight times faster than AutoMapper.

**Comment by anisimovyuriy** [comment]
Dear @JonPSmith,

Thanks a lot for your valuable input and appreciation.
Answering your questions:
1. Definitely YES, any contribution and PR is very welcome!

2. I think it is very good idea - actually you can follow the pattern like  ```.CaseSensitive(true)``` - it could be done on global and more granular level per mapping as you specified.

3. Definitely ```.Member```, ```.Ignore``` and other ```IMemberConfiguration``` methods should override flattening. There are some collections inside of ```TypeMapperBase``` and others e.g. ```.Ignore``` collection or overriden ```.Member``` collection where you can implement priority.

Just a standard gitflow - you can make a fork and then create Pull Request (PR) that will be reviewed and merged to the master branch of Expressmapper.

P.S. - Concerning LINQ projections from the runtime performance they are completely the same as there is no mapping happens - everything just converts to IQueryable<T>.Select(Expression);

Thanks a lot!

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

Thanks for the positive feedback. I am working on another project but I hope to fit this work around that. I expect I will have plenty of questions when I start, so watch this space. I'll also try and help with documentation, samples and articles as I think they are a important part of a successful open-source project.

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

Ok. I have looked at the code and I have some questions.

### Flatten/UnFlatten
Unlike AutoMapper ExpressMapper set up a two-way mapping by default. If I supported that then I would need to write a flatten **and** unflatten method. While flattening is doable unflattening, i.e. splitting one class has some parts that are impossible - a extreme case is if you took the count of an IEnumerable collection then you can't recreate the collection, but there are many other edge cases that are hard/impossible to handle.

Because of this I suggest I create a `Mapper.RegisterFlatten()`, or maybe a `Mapper.Register(fatten: true)`, which only creates a single source to destination mapping. 

Does that make sense? Are you happy with that?

### Some questions
Looking at the code I can see that I would add something to the `CompileInternal()` method in the class SourceTypeMapper. Below is a snippet of what I am thinking:

```csharp
        protected override void CompileInternal()
        {
            if (ResultMapFunction != null) return;

            var destVariable = GetDestionationVariable();

            ProcessCustomMembers();
            ProcessCustomFunctionMembers();
            ProcessFlattening(flattenThisMap);      //my new code
            ProcessAutoProperties();
            //... rest of the method
```
My idea is that `ProcessFlattening` will produce the same output as `ProcessCustomMembers()`, but in a new list for clarity of code/separation. If so my questions are:

1. How does `ProcessAutoProperties()` know to not set up the the destination that the CustomMembers have set up, e.g. where the user overrides a normal mapping using a `.Member()` call. I ask as I obviously need `ProcessAutoProperties()` to ignore the destinations that my new `ProcessFlattening` has set up.
2. You seem to produce two results: a `ResultMapFunction` and `QueryableExpression`. It looks like I need to add code to the `CreateQueryableProjection()` method in class SourceTypeMapper, but the  `ResultMapFunction` should just work, if the filter out of 'flattened' members is correct. Am I missing anything here?

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

I didn't hear back so I did some work to try an implement flattening, which now works. You can see it in action in one of my [Unit Tests](https://github.com/JonPSmith/TryMappers/blob/master/TryMappers/UnitTests/Test50FlattenExpressMapperEntityFramework.cs).

To minimise the changes to ExpressMapper I linked into the existing `CustomMembers` list by adding a few new methods. I then created a [separate project](https://github.com/JonPSmith/TryMappers/tree/master/TryMappers/Flatteners) to which has the flattening code in with its Unit Tests.

I have two options:
1. Do a pull request on the small changes I have made to ExpressMapper and create a separate package with the flattener code in, called something like ExpressMapper.Flattener.
2. Move my flatten code (four file, plus loads of Unit Tests) into ExpressMapper so that its all one package.

The first is easier in the short term, but the second is better in the long term. **What do you want me to do?**

*NOTE: If you want to try the flattener then you need to copy/fork [my Expressmapper](https://github.com/JonPSmith/ExpressMapper) and copy/fork [TryMapper](https://github.com/JonPSmith/TryMappers). You need to compile my ExpressMapper first and then add its .dll file into TryMapper. A kludge, but simple for a test development.*

**Comment by anisimovyuriy** [comment]
Dear @JonPSmith ,

My apologies for not responding - had difficulties to allocate any spare time for Expressmapper.
Thanks a lot for your contribution! Definitely I'd appreciate the second point : _"Move my flatten code (four files, plus loads of Unit Tests) into ExpressMapper so that its all one package."_ - Looking forward towards your PR.

Gratefully Yours,
Yuriy

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

No worries. I have the same problem with other work, so I might be a bit slow on implementing this for the same reason.

I will implement it in just the .NET4 version for now so you can check it out.

Jon

**Comment by anisimovyuriy** [comment]
Thank you @JonPSmith - looking forward towards your PR.

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

I have been working on this project and have a problem I would like your advice on. 

I have written some tests for [direct mapping](https://github.com/JonPSmith/ExpressMapper/blob/master/ExpressMapper.Tests%20NET40/FlattenTests.cs) and they work fine. When I create similar [tests using IQueryable `Project`](https://github.com/JonPSmith/ExpressMapper/blob/master/ExpressMapper.Tests%20NET40/FlattenProjectTests.cs). 

One of them called `FlattenCircularReferenceDtoOk` (line 137) throws the following error

```
System.NullReferenceException : Object reference not set to an instance of an object.

   at lambda_method(Closure , FlattenCircularReference )
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ExpressMapper.Tests.FlattenProjectTests.FlattenCircularReferenceDtoOk() in C:\Users\Jon\Documents\Visual Studio 2015\Projects\ExpressMapper\ExpressMapper.Tests NET40\FlattenProjectTests.cs:line 149
```

As you will see in the test I have commented out my `.FlattenSource` code and written it longhand. Can you tell me why that fails?

-----

Second issue is the test `FlattenFatherSonGrandsonDtoNoGrandson` (line 37) fails, which I thought might be the case (AutoMapper fails on this too). The error is
```
System.NullReferenceException : Object reference not set to an instance of an object.

   at lambda_method(Closure , Father )
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ExpressMapper.Tests.FlattenProjectTests.FlattenFatherSonGrandsonDtoNoGrandson() in C:\Users\Jon\Documents\Visual Studio 2015\Projects\ExpressMapper\ExpressMapper.Tests NET40\FlattenProjectTests.cs:line 47
```
As I say AutoMapper fails too. However I saw in your documentation the phase.
> Don't worry about null checks for nested object type properties - they are handled automatically for you. 

Is that only for direct mapping and not the case for `Project`?

**Comment by anisimovyuriy** [comment]
Thank you @JonPSmith! I will try to release ASAP (1-3 days) - would like to check that everything in place from the unit tests perspective and implementation.

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy and anyone else who is interested,

I have written a article called [Flattening Entity Framework relationships with ExpressMapper](http://www.thereformedprogrammer.net/flattening-entity-framework-relationships-with-expressmapper/) which covers why flattening is useful in relational databases and then gets into how ExpressMapper's new flattening feature (available now in version 1.8.1) work. The article is quite comprehensive (i.e. long!), but hopefully useful.

Hopefully the title will get picked up by the search engines and raise awareness on what ExpressMapper can do.

PS. If you spot anything that is wrong or unclear do leave me a comment on the article.

**Comment by anisimovyuriy** [comment]
Thank you @JonPSmith! Appreciate you help a lot!

**Comment by anisimovyuriy** [comment]
Great article @JonPSmith! I found one typo under the section "Introducing ExpressMapper" the word: "steup" instead of "setup".

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy. Fixed steup. 

PS. Glad you liked it. Lets see if anyone else likes it too.
