### ISSUE TITLE
Mapping nested class

### ISSUE THREAD

**Issue by JonPSmith** [expressmapper/ExpressMapper#91]
Hi,

As part of the work on flattening (see #85) I am looking at mapping a nested class to map in a similar way to how AutoMapper works. However when I try this with Expressmapper I get an error during the compile. The full test is available [here](https://github.com/JonPSmith/ExpressMapper/blob/master/ExpressMapper.Tests%20NET40/FlattenTests.cs) on line 54, but I have listed the code in one place to make it easier - note the problem is around the mapping of `scr.Son.Grandson` to a property that has a mapped class:

Consider classes like these as the input:

```csharp
    public class Father
    {
        public int MyInt { get; set; }
        public string MyString { get; set; }
        public Son Son { get; set; }
    }

    public class Son
    {
        public int MyInt { get; set; }
        public string MyString { get; set; }
        public Grandson Grandson { get; set; }
    }

    public class Grandson 
    {
        public int MyInt { get; set; }
        public string MyString { get; set; }
    }
```

And two DTOs like this

```csharp
    public class FlattenFatherSonDtoForGrandsonDto
    {
        public int MyInt { get; set; }
        public string MyString { get; set; }

        public int SonMyInt { get; set; }
        public string SonMyString { get; set; }

        public FlattenSimpleClass SonGrandson { get; set; }
    }

    public class FlattenSimpleClass
    {
        public int MyInt { get; set; }
        public string MyString { get; set; }
    }
```

If I set up a mapping like this then the compile fails

```csharp
Mapper.Reset();
Mapper.Register<Grandson, FlattenSimpleClass>();
Mapper.Register<Father, FlattenFatherSonDtoForGrandsonDto>() //.FlattenSource();
   .Member(dest => dest.SonMyInt, src => src.Son.MyInt)
   .Member(dest => dest.SonMyString, src => src.Son.MyString)
   .Member(dest => dest.SonGrandson, src => src.Son.Grandson);
Mapper.Compile(CompilationTypes.Source);
```

The error is:
```
ExpressMapper.ExpressmapperException : Error error occured trying to compile mapping for: source ExpressMapper.Tests.Model.Models.Father, destination ExpressMapper.Tests.Model.ViewModels.FlattenFatherSonDtoForGrandsonDto. See the inner exception for details.
  ----> System.ArgumentException : Argument types do not match
```

which is caused by the like `.Member(dest => dest.SonGrandson, src => src.Son.Grandson);`

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

Having traced the code it fails on line 187 in `MappingServiceBase`. My reading of this is that ExpressMapper does not currently handle mappings in custom member definitions. Whether that is something that can be added or not I am not sure, but it bound to be something that AutoMapper users will be used to in flattening.

Any suggestions?

**Comment by anisimovyuriy** [comment]
Hi @JonPSmith,

Let me check this case and I'll get back to you. Thanks for your contribution. 
P.S. - I'll try to check your PR ASAP!

Gratefully Yours,
Yuriy

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

Great. On the PR then I wasn't sure what to do about the other .NET versions. It *looked* like I just added the three files as linked files, but I wasn't sure. I have another version (which follows your case sensitive conventions) ready to send over so I can fix the other .NET versions if you let me know.

On this mapping nested classes on customer mappings I think its doable, but you know your code better than me! Its not a deal breaker, but someone is bound to say it doesn't do it!

Jon

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

A bit more digging on this problem show that it goes wrong inside `GetMemberMappingExpression` on line 192 of the file MappingServiceBase.cs. The code below.

```csharp
                return nullCheckNestedMemberVisitor.CheckNullExpression != null
                    ? Expression.Condition(nullCheckNestedMemberVisitor.CheckNullExpression,
                        Expression.Assign(left, Expression.Default(left.Type)),
                        mapComplexResult)
                    : mapComplexResult;
```

I kinda see what is going on. Looks like you don't allow ExpressMapping inside a custom member statement. Would that be hard to do? Happy to help if you give me some directions.
I think

**Comment by anisimovyuriy** [comment]
I'm about to create PR for your PR - it's been fixed there.
